# Generated by Django 4.2.7 on 2024-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='document_proofs',
            field=models.ImageField(height_field='200px', upload_to='images', width_field='200px'),
        ),
    ]
