# Generated by Django 4.2.7 on 2024-01-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realestate', '0003_alter_tenant_document_proofs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant', to='realestate.tenant'),
        ),
    ]
